[project]
dependencies = [
  "click>=8.1.7",
  "xmlschema==2.5.0"
]
description = "Build xml from xsd"
name = "xsd2xml"
requires-python = ">=3.9"
version = "0.0.1"

[project.scripts]
xsd2xml = "app.xsd2xml:cli"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]